spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi?useTimezone=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    url: jdbc:mysql://localhost:3306/restapi?useTimezone=true&serverTimezone=UTC
    user: root
    password: password
    locations: classpath:db/migration
    baseline-on-migrate: true
